/**
 * Search Data Index
 * Contains all searchable items across the site for unified search.
 * [TRACE: DOCS/ARCHITECTURE.md]
 */
var SEARCH_DATA = [
    // === PROJECTS (programs.html) ===
    { title: "3JS Body Baker", desc: "Three.js character model maker with preset parts and customizable models.", category: "project", tags: ["HTML", "Three.js", "3D Modeling"], url: "programs.html" },
    { title: "Aethereal Hymns", desc: "AI-powered dynamic music generation system for RPG games and interactive experiences.", category: "project", tags: ["Python", "AI", "Music"], url: "programs.html" },
    { title: "Better-Me", desc: "Habit tracking and routine management tool for personal development.", category: "project", tags: ["TypeScript", "Productivity", "Habits"], url: "programs.html" },
    { title: "BlockBanger", desc: "Browser-based music maker with block-based composition.", category: "project", tags: ["JavaScript", "Music", "Browser"], url: "programs.html" },
    { title: "Chipper Chopper", desc: "Minecraft woodcutting bot experiment.", category: "project", tags: ["Java", "Minecraft", "Bot"], url: "programs.html" },
    { title: "Click-It-Goin", desc: "Infinite clicker game with golden cookie events and prestige system.", category: "project", tags: ["JavaScript", "Game", "Browser"], url: "programs.html" },
    { title: "Dagda Server Manager", desc: "Desktop server management tool with Celtic mythology theme and real-time monitoring.", category: "project", tags: ["Python", "Tkinter", "Server"], url: "programs.html" },
    { title: "Feeshman Deelux", desc: "Minecraft fishing bot with automated mechanics and loot tracking.", category: "project", tags: ["Minecraft", "Bot", "Automation"], url: "programs.html" },
    { title: "FireFest", desc: "3D first-person shooter built with Three.js.", category: "project", tags: ["TypeScript", "Three.js", "FPS"], url: "programs.html" },
    { title: "GaelDrive", desc: "3D open world car game inspired by Gaelic and Irish culture.", category: "project", tags: ["JavaScript", "3D", "Open World"], url: "programs.html" },
    { title: "JeSsy-Assety", desc: "Professional asset management system for game developers with OpenGameArt integration.", category: "project", tags: ["JavaScript", "Flask", "Game Dev"], url: "programs.html" },
    { title: "Nebula-Camera", desc: "Advanced Android camera app with AI features.", category: "project", tags: ["Kotlin", "Android", "Camera"], url: "programs.html" },
    { title: "Nebula-Chat", desc: "AI chat application with multiple provider support.", category: "project", tags: ["TypeScript", "AI", "Chat"], url: "programs.html" },
    { title: "Nexus Engine", desc: "AI-first game engine with natural language APIs and ECS architecture.", category: "project", tags: ["Python", "Pygame", "AI"], url: "programs.html" },
    { title: "Pop-Em Pictures", desc: "In-game repetitive, customizable screenshot taking tool.", category: "project", tags: ["Python", "Automation", "Screenshots"], url: "programs.html" },
    { title: "Proof Of Purchase", desc: "Receipt scanner application with budget analytics and company profiling.", category: "project", tags: ["Kotlin", "Scanner", "Finance"], url: "programs.html" },
    { title: "RAIN.CHAT v2", desc: "Local AI-native IDE with zero cloud dependencies and built-in AI inference engine.", category: "project", tags: ["Rust", "AI", "IDE"], url: "programs.html" },
    { title: "RunicOS", desc: "Modern web-based operating system built with Svelte 5 and real-time WebSocket updates.", category: "project", tags: ["JavaScript", "Svelte", "WebOS"], url: "programs.html" },
    { title: "Simpleton CLI", desc: "AI agent-based CLI development tool for streamlined command-line workflows.", category: "project", tags: ["TypeScript", "CLI", "AI Agent"], url: "programs.html" },
    { title: "Pixel-Perfect", desc: "Pixel art editor with advanced drawing tools.", category: "project", tags: ["Python", "Art", "Editor"], url: "programs.html" },

    // === AI CHATS (chats.html) ===
    { title: "ChatGPT", desc: "OpenAI's conversational AI assistant with GPT-4 and beyond.", category: "chat", tags: ["OpenAI", "GPT-4", "Assistant"], url: "chats.html" },
    { title: "Claude", desc: "Anthropic's helpful, harmless, and honest AI assistant.", category: "chat", tags: ["Anthropic", "Claude", "Assistant"], url: "chats.html" },
    { title: "Gemini", desc: "Google's multimodal AI assistant with advanced reasoning.", category: "chat", tags: ["Google", "Gemini", "Multimodal"], url: "chats.html" },
    { title: "Grok", desc: "xAI's witty AI with real-time X integration.", category: "chat", tags: ["xAI", "Grok", "X"], url: "chats.html" },
    { title: "Copilot", desc: "Microsoft's AI companion powered by GPT-4.", category: "chat", tags: ["Microsoft", "Copilot", "GPT-4"], url: "chats.html" },
    { title: "Meta AI", desc: "Meta's conversational AI assistant.", category: "chat", tags: ["Meta", "Llama", "Assistant"], url: "chats.html" },
    { title: "DeepSeek", desc: "Advanced reasoning AI with chain-of-thought capabilities.", category: "chat", tags: ["DeepSeek", "Reasoning", "AI"], url: "chats.html" },
    { title: "Mistral", desc: "Open-weight AI models from Mistral AI.", category: "chat", tags: ["Mistral", "Open Source", "AI"], url: "chats.html" },
    { title: "NotebookLM", desc: "Google's AI-powered research and note-taking assistant.", category: "chat", tags: ["Google", "Research", "Notes"], url: "chats.html" },
    { title: "Poe", desc: "Quora's multi-bot AI chat platform.", category: "chat", tags: ["Quora", "Multi-bot", "Platform"], url: "chats.html" },
    { title: "Character.AI", desc: "Chat with AI-powered characters and personas.", category: "chat", tags: ["Characters", "Roleplay", "AI"], url: "chats.html" },
    { title: "OpenRouter", desc: "Unified API for multiple AI models.", category: "chat", tags: ["API", "Multi-model", "Router"], url: "chats.html" },
    { title: "Together.ai", desc: "Fast inference platform for open-source models.", category: "chat", tags: ["Inference", "Open Source", "Fast"], url: "chats.html" },
    { title: "Groq", desc: "Lightning-fast AI inference with LPU technology.", category: "chat", tags: ["Groq", "Fast", "LPU"], url: "chats.html" },
    { title: "SambaNova", desc: "Enterprise AI with custom silicon.", category: "chat", tags: ["Enterprise", "Silicon", "AI"], url: "chats.html" },
    { title: "Cerebras", desc: "AI inference on wafer-scale chips.", category: "chat", tags: ["Cerebras", "Wafer", "Fast"], url: "chats.html" },
    { title: "HuggingChat", desc: "Hugging Face chat with open-source models.", category: "chat", tags: ["Hugging Face", "Open Source", "Chat"], url: "chats.html" },

    // === MEDIA GENERATION (media.html) ===
    { title: "DALL-E 3", desc: "OpenAI's advanced image generation model.", category: "media", tags: ["OpenAI", "Image", "Generation"], url: "media.html" },
    { title: "Midjourney", desc: "Premium AI art generation with stunning aesthetics.", category: "media", tags: ["Art", "Image", "Premium"], url: "media.html" },
    { title: "Stable Diffusion", desc: "Open-source image generation model.", category: "media", tags: ["Open Source", "Image", "Stability"], url: "media.html" },
    { title: "Ideogram", desc: "AI image generator with excellent text rendering.", category: "media", tags: ["Image", "Text", "Art"], url: "media.html" },
    { title: "Leonardo.AI", desc: "AI art generation with fine-tuned models.", category: "media", tags: ["Art", "Game Assets", "AI"], url: "media.html" },
    { title: "Recraft", desc: "Vector and raster AI image generation.", category: "media", tags: ["Vector", "Design", "AI"], url: "media.html" },
    { title: "Sora", desc: "OpenAI's text-to-video generation model.", category: "media", tags: ["Video", "OpenAI", "Generation"], url: "media.html" },
    { title: "Runway", desc: "AI video editing and generation platform.", category: "media", tags: ["Video", "Editing", "AI"], url: "media.html" },
    { title: "Pika", desc: "AI video generation and editing.", category: "media", tags: ["Video", "Generation", "AI"], url: "media.html" },
    { title: "Luma AI", desc: "3D and video AI generation.", category: "media", tags: ["3D", "Video", "AI"], url: "media.html" },
    { title: "ElevenLabs", desc: "AI voice synthesis and cloning.", category: "media", tags: ["Voice", "TTS", "Clone"], url: "media.html" },
    { title: "Suno", desc: "AI music generation from text prompts.", category: "media", tags: ["Music", "Generation", "AI"], url: "media.html" },
    { title: "Udio", desc: "AI-powered music creation platform.", category: "media", tags: ["Music", "Generation", "AI"], url: "media.html" },
    { title: "HeyGen", desc: "AI avatar video generation.", category: "media", tags: ["Avatar", "Video", "AI"], url: "media.html" },
    { title: "Synthesia", desc: "AI video generation with digital avatars.", category: "media", tags: ["Avatar", "Video", "Enterprise"], url: "media.html" },
    { title: "Hugging Face Spaces", desc: "1M+ AI apps: image, video, audio, chat; host and discover.", category: "media", tags: ["Hugging Face", "Spaces", "Apps"], url: "media.html" },

    // === COMPANIES (companies.html) ===
    { title: "OpenAI", desc: "Creator of GPT, DALL-E, and Sora. Leading AI research lab.", category: "company", tags: ["GPT", "ChatGPT", "Research"], url: "companies.html" },
    { title: "Anthropic", desc: "AI safety company, creator of Claude.", category: "company", tags: ["Claude", "Safety", "Research"], url: "companies.html" },
    { title: "Google DeepMind", desc: "Google's AI research division behind Gemini.", category: "company", tags: ["Gemini", "Research", "Google"], url: "companies.html" },
    { title: "Meta AI", desc: "Meta's AI division, creators of Llama models.", category: "company", tags: ["Llama", "Open Source", "Meta"], url: "companies.html" },
    { title: "Microsoft", desc: "AI through Azure, Copilot, and OpenAI partnership.", category: "company", tags: ["Copilot", "Azure", "Enterprise"], url: "companies.html" },
    { title: "xAI", desc: "Elon Musk's AI company, creator of Grok.", category: "company", tags: ["Grok", "X", "Elon Musk"], url: "companies.html" },
    { title: "Stability AI", desc: "Creator of Stable Diffusion and open AI models.", category: "company", tags: ["Stable Diffusion", "Open Source", "Image"], url: "companies.html" },
    { title: "Mistral AI", desc: "European AI company with powerful open models.", category: "company", tags: ["Open Source", "European", "Models"], url: "companies.html" },
    { title: "Cohere", desc: "Enterprise NLP and embedding models.", category: "company", tags: ["NLP", "Enterprise", "Embeddings"], url: "companies.html" },
    { title: "Perplexity", desc: "AI-powered search engine with citations.", category: "company", tags: ["Search", "AI", "Citations"], url: "companies.html" },
    { title: "Hugging Face", desc: "Models (2M+), datasets (500k+), Spaces (1M+ apps), HuggingChat.", category: "company", tags: ["Open Source", "Models", "Hub"], url: "companies.html" },
    { title: "MongoDB", desc: "Atlas: document DB, vector search, stream processing; AI-ready.", category: "company", tags: ["Database", "Atlas", "Vector Search"], url: "companies.html" },
    { title: "NVIDIA", desc: "AI hardware and software ecosystem leader.", category: "company", tags: ["GPU", "Hardware", "CUDA"], url: "companies.html" },
    { title: "Rosebud AI", desc: "Vibe coding: 2D/3D games and worlds with AI; Game Creator, PixelVibe.", category: "company", tags: ["Game Dev", "AI", "Vibe Coding"], url: "companies.html" },
    { title: "itch.io", desc: "Indie game store: free/paid games, jams, dev portal, assets.", category: "company", tags: ["Games", "Indie", "Dev Portal"], url: "companies.html" },
    { title: "Armor Games", desc: "Free online games: action, puzzle, strategy, MMO, dev portal.", category: "company", tags: ["Games", "Browser", "Free"], url: "companies.html" },
    { title: "Newgrounds", desc: "Classic portal: games, art, audio; Flash legacy, indie community.", category: "company", tags: ["Games", "Indie", "Portal"], url: "companies.html" },
    { title: "PlayHop", desc: "Free browser games platform.", category: "company", tags: ["Games", "Browser", "Free"], url: "companies.html" },
    { title: "Yandex", desc: "Yandex Games: play in browser.", category: "company", tags: ["Games", "Browser", "Yandex"], url: "companies.html" },

    // === TOOLS (tools.html) ===
    { title: "Cursor", desc: "AI-first code editor built on VS Code.", category: "tool", tags: ["IDE", "AI", "VS Code"], url: "tools.html" },
    { title: "Windsurf", desc: "AI-powered IDE by Codeium.", category: "tool", tags: ["IDE", "AI", "Codeium"], url: "tools.html" },
    { title: "Zed", desc: "High-performance code editor with AI built-in.", category: "tool", tags: ["IDE", "Performance", "Rust"], url: "tools.html" },
    { title: "GitHub Copilot", desc: "AI pair programmer in your IDE.", category: "tool", tags: ["AI", "Coding", "GitHub"], url: "tools.html" },
    { title: "Aider", desc: "AI pair programming in your terminal.", category: "tool", tags: ["CLI", "AI", "Terminal"], url: "tools.html" },
    { title: "Claude Code", desc: "Anthropic's agentic coding tool.", category: "tool", tags: ["CLI", "Anthropic", "Agent"], url: "tools.html" },
    { title: "Gemini CLI", desc: "Google's AI assistant in the terminal.", category: "tool", tags: ["CLI", "Google", "Terminal"], url: "tools.html" },
    { title: "OpenAI Codex CLI", desc: "OpenAI's coding assistant CLI.", category: "tool", tags: ["CLI", "OpenAI", "Coding"], url: "tools.html" },
    { title: "Bolt", desc: "AI-powered full-stack app builder.", category: "tool", tags: ["Browser", "Full-stack", "AI"], url: "tools.html" },
    { title: "Replit", desc: "Cloud IDE with AI code generation.", category: "tool", tags: ["Browser", "Cloud", "IDE"], url: "tools.html" },
    { title: "Firebase", desc: "Google: hosting, Firestore, Auth, Firebase ML, AI (Studio, Gemini in Firebase, Genkit).", category: "tool", tags: ["Google", "Hosting", "Database", "ML"], url: "tools.html" },
    { title: "MongoDB", desc: "Atlas: document DB, vector search, stream processing; AI-ready platform.", category: "tool", tags: ["Database", "Atlas", "Vector Search"], url: "tools.html" },
    { title: "Hugging Face", desc: "Models (2M+), datasets (500k+), Spaces (1M+ apps); Inference, HuggingChat.", category: "tool", tags: ["Models", "Datasets", "Spaces"], url: "tools.html" },
    { title: "StackBlitz", desc: "Instant web development environment.", category: "tool", tags: ["Browser", "Web", "Instant"], url: "tools.html" },
    { title: "v0.dev", desc: "Vercel's AI UI component generator.", category: "tool", tags: ["UI", "Vercel", "Components"], url: "tools.html" },
    { title: "Localtunnel", desc: "Expose localhost to the web instantly.", category: "tool", tags: ["Tunneling", "Localhost", "Free"], url: "tools.html" },
    { title: "Tunnelmole", desc: "Simple tunneling for local development.", category: "tool", tags: ["Tunneling", "Simple", "Dev"], url: "tools.html" },
    { title: "TRAE", desc: "10x AI engineer; build software solutions independently.", category: "tool", tags: ["IDE", "AI", "Agent"], url: "tools.html" },
    { title: "Warp", desc: "Agentic terminal and IDE with full terminal use.", category: "tool", tags: ["Terminal", "IDE", "Agent"], url: "tools.html" },
    { title: "Factory", desc: "Agent-native dev; Droids in IDE, web, CLI, Slack.", category: "tool", tags: ["Agent", "IDE", "Droids"], url: "tools.html" },
    { title: "Google Antigravity", desc: "Google's agentic IDE; autonomous agents across editor, terminal, browser.", category: "tool", tags: ["Google", "IDE", "Agent"], url: "tools.html" },
    { title: "Android Studio", desc: "Official Android IDE with Gemini in Android Studio.", category: "tool", tags: ["Android", "IDE", "Google"], url: "tools.html" },
    { title: "Kimi Code CLI", desc: "Moonshot AI terminal agent; MCP, ACP, VS Code extension.", category: "tool", tags: ["CLI", "Moonshot", "MCP"], url: "tools.html" },
    { title: "Mistral Vibe", desc: "Mistral's open-source CLI coding assistant; skills, MCP.", category: "tool", tags: ["CLI", "Mistral", "MCP"], url: "tools.html" },
    { title: "Crush", desc: "Charm's agentic CLI; multi-model, LSP, MCP, sessions.", category: "tool", tags: ["CLI", "Charm", "Agent"], url: "tools.html" },
    { title: "Qwen Code", desc: "QwenLM open-source terminal agent; OAuth free tier, IDE integration.", category: "tool", tags: ["CLI", "Qwen", "Open Source"], url: "tools.html" },
    { title: "Docker", desc: "Containers, MCP catalog, agentic stack with Compose.", category: "tool", tags: ["Containers", "MCP", "DevOps"], url: "tools.html" },
    { title: "Claude (desktop & mobile)", desc: "Download Claude app for macOS, Windows, iOS, Android.", category: "tool", tags: ["Claude", "Download", "Anthropic"], url: "tools.html" },
    { title: "HTML Online Viewer", desc: "Edit and preview HTML in the browser; format, highlight.", category: "tool", tags: ["HTML", "Browser", "Preview"], url: "tools.html" },
    { title: "Wispr Flow", desc: "AI voice dictation; speech to polished text in every app (Mac, Windows, iPhone).", category: "tool", tags: ["Voice", "Speech-to-text", "Dictation"], url: "tools.html" },
    { title: "Rosebud AI", desc: "Vibe coding: make 2D/3D games and worlds with AI; no code, browser.", category: "tool", tags: ["Game Dev", "AI", "Vibe Coding"], url: "tools.html" },
    { title: "itch.io (game dev)", desc: "Indie dev portal: publish games, assets, jams, dev logs.", category: "tool", tags: ["Game Dev", "Indie", "Portal"], url: "tools.html" },

    // === SPECIALS (specials.html) ===
    { title: "DigitalPlat FreeDomain", desc: "Get free domain names for your projects.", category: "special", tags: ["Domain", "Free", "Hosting"], url: "specials.html" },
    { title: "freeCodeCamp", desc: "Learn to code for free with comprehensive curriculum.", category: "special", tags: ["Learning", "Free", "Coding"], url: "specials.html" },
    { title: "The Odin Project", desc: "Full-stack curriculum for web development.", category: "special", tags: ["Learning", "Full-stack", "Free"], url: "specials.html" },
    { title: "itch.io", desc: "Indie game store: free/paid games, jams, dev portal, assets.", category: "special", tags: ["Games", "Indie", "Dev Portal"], url: "specials.html" },
    { title: "Armor Games", desc: "Free online games: action, puzzle, strategy, RPG, MMO.", category: "special", tags: ["Games", "Browser", "Free"], url: "specials.html" },
    { title: "PlayHop", desc: "Free browser games platform.", category: "special", tags: ["Games", "Browser", "Free"], url: "specials.html" },
    { title: "Newgrounds", desc: "Classic portal: games, art, audio; Flash legacy, indie dev.", category: "special", tags: ["Games", "Indie", "Portal"], url: "specials.html" },
    { title: "Yandex Games", desc: "Yandex game portal: play in browser.", category: "special", tags: ["Games", "Browser", "Yandex"], url: "specials.html" },

    // === PAGES ===
    { title: "Home", desc: "Ryan Otterdays developer profile and overview.", category: "page", tags: ["Profile", "Home", "About"], url: "index.html" },
    { title: "Programs", desc: "Browse 60+ projects including games, tools, and AI projects.", category: "page", tags: ["Projects", "Portfolio", "Code"], url: "programs.html" },
    { title: "AI Chats", desc: "Links to AI chat platforms and assistants.", category: "page", tags: ["AI", "Chat", "Assistants"], url: "chats.html" },
    { title: "Media Gen", desc: "AI media generation tools for video, image, and audio.", category: "page", tags: ["Media", "Generation", "AI"], url: "media.html" },
    { title: "Companies", desc: "55+ AI and tech companies directory.", category: "page", tags: ["Companies", "Directory", "AI"], url: "companies.html" },
    { title: "Tools", desc: "Developer tools including CLI, IDE, and browser tools.", category: "page", tags: ["Tools", "Developer", "IDE"], url: "tools.html" },
    { title: "Specials", desc: "Free resources, domains, learning, and games (itch.io, Armor Games, PlayHop, Newgrounds, Yandex Games).", category: "page", tags: ["Free", "Resources", "Learning", "Games"], url: "specials.html" },
    { title: "About", desc: "What this site is: projects and tools worth sharing. Every link is safe and direct.", category: "page", tags: ["About", "Site", "Links"], url: "about.html" }
];
