/**
 * Search Data Index
 * Contains all searchable items across the site for unified search.
 * [TRACE: DOCS/ARCHITECTURE.md]
 */
var SEARCH_DATA = [
    // === PROJECTS (programs.html) ===
    { title: "3JS Body Baker", desc: "Three.js character model maker with preset parts and customizable models.", category: "project", tags: ["HTML", "Three.js", "3D Modeling"], url: "programs.html" },
    { title: "Aethereal Hymns", desc: "AI-powered dynamic music generation system for RPG games and interactive experiences.", category: "project", tags: ["Python", "AI", "Music"], url: "programs.html" },
    { title: "Better-Me", desc: "Habit tracking and routine management tool for personal development.", category: "project", tags: ["TypeScript", "Productivity", "Habits"], url: "programs.html" },
    { title: "BlockBanger", desc: "Browser-based music maker with block-based composition.", category: "project", tags: ["JavaScript", "Music", "Browser"], url: "programs.html" },
    { title: "Chipper Chopper", desc: "Minecraft woodcutting bot experiment.", category: "project", tags: ["Java", "Minecraft", "Bot"], url: "programs.html" },
    { title: "Click-It-Goin", desc: "Infinite clicker game with golden cookie events and prestige system.", category: "project", tags: ["JavaScript", "Game", "Browser"], url: "programs.html" },
    { title: "Dagda Server Manager", desc: "Desktop server management tool with Celtic mythology theme and real-time monitoring.", category: "project", tags: ["Python", "Tkinter", "Server"], url: "programs.html" },
    { title: "Feeshman Deelux", desc: "Minecraft fishing bot with automated mechanics and loot tracking.", category: "project", tags: ["Minecraft", "Bot", "Automation"], url: "programs.html" },
    { title: "FireFest", desc: "3D first-person shooter built with Three.js.", category: "project", tags: ["TypeScript", "Three.js", "FPS"], url: "programs.html" },
    { title: "GaelDrive", desc: "3D open world car game inspired by Gaelic and Irish culture.", category: "project", tags: ["JavaScript", "3D", "Open World"], url: "programs.html" },
    { title: "JeSsy-Assety", desc: "Professional asset management system for game developers with OpenGameArt integration.", category: "project", tags: ["JavaScript", "Flask", "Game Dev"], url: "programs.html" },
    { title: "Nebula-Camera", desc: "Advanced Android camera app with AI features.", category: "project", tags: ["Kotlin", "Android", "Camera"], url: "programs.html" },
    { title: "Nebula-Chat", desc: "AI chat application with multiple provider support.", category: "project", tags: ["TypeScript", "AI", "Chat"], url: "programs.html" },
    { title: "Nexus Engine", desc: "AI-first game engine with natural language APIs and ECS architecture.", category: "project", tags: ["Python", "Pygame", "AI"], url: "programs.html" },
    { title: "Pop-Em Pictures", desc: "In-game repetitive, customizable screenshot taking tool.", category: "project", tags: ["Python", "Automation", "Screenshots"], url: "programs.html" },
    { title: "Proof Of Purchase", desc: "Receipt scanner application with budget analytics and company profiling.", category: "project", tags: ["Kotlin", "Scanner", "Finance"], url: "programs.html" },
    { title: "RAIN.CHAT v2", desc: "Local AI-native IDE with zero cloud dependencies and built-in AI inference engine.", category: "project", tags: ["Rust", "AI", "IDE"], url: "programs.html" },
    { title: "RunicOS", desc: "Modern web-based operating system built with Svelte 5 and real-time WebSocket updates.", category: "project", tags: ["JavaScript", "Svelte", "WebOS"], url: "programs.html" },
    { title: "Simpleton CLI", desc: "AI agent-based CLI development tool for streamlined command-line workflows.", category: "project", tags: ["TypeScript", "CLI", "AI Agent"], url: "programs.html" },
    { title: "Pixel-Perfect", desc: "Pixel art editor with advanced drawing tools.", category: "project", tags: ["Python", "Art", "Editor"], url: "programs.html" },

    // === AI CHATS (chats.html) ===
    { title: "ChatGPT", desc: "OpenAI's conversational AI assistant with GPT-4 and beyond.", category: "chat", tags: ["OpenAI", "GPT-4", "Assistant"], url: "chats.html" },
    { title: "Claude", desc: "Anthropic's helpful, harmless, and honest AI assistant.", category: "chat", tags: ["Anthropic", "Claude", "Assistant"], url: "chats.html" },
    { title: "Gemini", desc: "Google's multimodal AI assistant with advanced reasoning.", category: "chat", tags: ["Google", "Gemini", "Multimodal"], url: "chats.html" },
    { title: "Grok", desc: "xAI's witty AI with real-time X integration.", category: "chat", tags: ["xAI", "Grok", "X"], url: "chats.html" },
    { title: "Copilot", desc: "Microsoft's AI companion powered by GPT-4.", category: "chat", tags: ["Microsoft", "Copilot", "GPT-4"], url: "chats.html" },
    { title: "Meta AI", desc: "Meta's conversational AI assistant.", category: "chat", tags: ["Meta", "Llama", "Assistant"], url: "chats.html" },
    { title: "DeepSeek", desc: "Advanced reasoning AI with chain-of-thought capabilities.", category: "chat", tags: ["DeepSeek", "Reasoning", "AI"], url: "chats.html" },
    { title: "Le Chat (Mistral)", desc: "Open-weight AI models from Mistral AI. Try Le Chat.", category: "chat", tags: ["Mistral", "Le Chat", "Open Source", "AI"], url: "chats.html" },
    { title: "NotebookLM", desc: "Google's AI-powered research and note-taking assistant.", category: "chat", tags: ["Google", "Research", "Notes"], url: "chats.html" },
    { title: "Poe", desc: "Quora's multi-bot AI chat platform.", category: "chat", tags: ["Quora", "Multi-bot", "Platform"], url: "chats.html" },
    { title: "Character.AI", desc: "Chat with AI-powered characters and personas.", category: "chat", tags: ["Characters", "Roleplay", "AI"], url: "chats.html" },
    { title: "OpenRouter", desc: "Unified API for multiple AI models.", category: "chat", tags: ["API", "Multi-model", "Router"], url: "chats.html" },
    { title: "Together.ai", desc: "Fast inference platform for open-source models.", category: "chat", tags: ["Inference", "Open Source", "Fast"], url: "chats.html" },
    { title: "Groq", desc: "Lightning-fast AI inference with LPU technology.", category: "chat", tags: ["Groq", "Fast", "LPU"], url: "chats.html" },
    { title: "SambaNova", desc: "Enterprise AI with custom silicon.", category: "chat", tags: ["Enterprise", "Silicon", "AI"], url: "chats.html" },
    { title: "Arena", desc: "Benchmark and compare the best AI models; experience the frontier; battle, leaderboard.", category: "chat", tags: ["Benchmark", "Multi-model", "Leaderboard"], url: "chats.html" },
    { title: "Cerebras", desc: "AI inference on wafer-scale chips.", category: "chat", tags: ["Cerebras", "Wafer", "Fast"], url: "chats.html" },
    { title: "HuggingChat", desc: "Hugging Face chat with open-source models.", category: "chat", tags: ["Hugging Face", "Open Source", "Chat"], url: "chats.html" },
    { title: "Chat LLM", desc: "Free chat with 1096+ AI models in one place.", category: "chat", tags: ["Multi-model", "Free", "LLM"], url: "chats.html" },
    { title: "Higgsfield Assist", desc: "Creative copilot for prompts and storyboards; video and image workflows.", category: "chat", tags: ["Higgsfield", "Creative", "Storyboards"], url: "chats.html" },
    { title: "Lumio AI", desc: "India's multi-LLM platform: GPT-4o, Claude, Gemini, DeepSeek, Mistral, Grok in one workspace.", category: "chat", tags: ["Multi-model", "India", "LLM"], url: "chats.html" },
    { title: "Sup AI", desc: "Multi-model orchestration; research-grade accuracy, logprob confidence scoring, always cited.", category: "chat", tags: ["Multi-model", "Accuracy", "Orchestration"], url: "chats.html" },
    { title: "WebLLM Chat", desc: "Browser-based LLM chat; run models in the browser.", category: "chat", tags: ["Browser", "LLM", "WebLLM"], url: "chats.html" },
    { title: "Deep Cogito", desc: "Multi-model chat (Cogito 671B, 405B, 109B, 70B); ask anything.", category: "chat", tags: ["Multi-model", "Cogito", "Chat"], url: "chats.html" },
    { title: "Dolphin Chat", desc: "Dolphin models; chat, bot, models, network, docs.", category: "chat", tags: ["Dolphin", "Chat", "Models"], url: "chats.html" },
    { title: "Falcon (TII)", desc: "Technology Innovation Institute: Falcon H1R 7B, H1 Arabic; try our chat.", category: "chat", tags: ["Falcon", "TII", "Open Source"], url: "chats.html" },
    { title: "K2 Think", desc: "MBZUAI open-source reasoning model; ask anything.", category: "chat", tags: ["MBZUAI", "Reasoning", "Open Source"], url: "chats.html" },
    { title: "LongCat AI", desc: "More than fast: think, search, generate image and video.", category: "chat", tags: ["LongCat", "Multimodal", "Chat"], url: "chats.html" },
    { title: "Nous Chat", desc: "Hermes models (e.g. 4-405B); worldbuilding, code, reasoning.", category: "chat", tags: ["Nous", "Hermes", "Chat"], url: "chats.html" },
    { title: "Public AI", desc: "Try Apertus: open-source LLM from public institution (Switzerland).", category: "chat", tags: ["Apertus", "Open Source", "Public AI"], url: "chats.html" },
    { title: "StepFun", desc: "Chat, knowledge-base Q&A, image creation, Step Audio Studio.", category: "chat", tags: ["StepFun", "Chat", "Audio"], url: "chats.html" },
    { title: "Tencent Hunyuan", desc: "Hunyuan AI Studio: dialogue, multimodal, model access, research.", category: "chat", tags: ["Tencent", "Hunyuan", "Multimodal"], url: "chats.html" },
    { title: "ZenMux", desc: "Unified gateway to many models; chat and API; compensation for subpar results.", category: "chat", tags: ["Multi-model", "API", "Gateway"], url: "chats.html" },
    { title: "OpenClaw", desc: "Viral personal AI assistant hosted on your system.", category: "chat", tags: ["Personal", "Hosted", "Assistant"], url: "chats.html" },
    { title: "Moltbook", desc: "AI-only social platform; chat and share with AI.", category: "chat", tags: ["Social", "AI", "Platform"], url: "chats.html" },
    { title: "T3 Chat", desc: "Fast AI chatbot; multi-model; by theo gg.", category: "chat", tags: ["theo gg", "T3", "Multi-model", "Chat"], url: "chats.html" },
    { title: "Llama 4", desc: "Meta's open-source multimodal; custom builds, self-host.", category: "chat", tags: ["Meta", "Llama", "Open Source", "Multimodal"], url: "chats.html" },

    // === MEDIA GENERATION (media.html) ===
    { title: "DALL-E 3", desc: "OpenAI's advanced image generation model.", category: "media", tags: ["OpenAI", "Image", "Generation"], url: "media.html" },
    { title: "Midjourney", desc: "Premium AI art generation with stunning aesthetics.", category: "media", tags: ["Art", "Image", "Premium"], url: "media.html" },
    { title: "Stable Diffusion", desc: "Open-source image generation model.", category: "media", tags: ["Open Source", "Image", "Stability"], url: "media.html" },
    { title: "Ideogram", desc: "AI image generator with excellent text rendering.", category: "media", tags: ["Image", "Text", "Art"], url: "media.html" },
    { title: "T3 Canvas", desc: "AI image studio: generate, compare, iterate; by theo gg.", category: "media", tags: ["Image", "theo gg", "Studio"], url: "media.html" },
    { title: "Leonardo.AI", desc: "AI art generation with fine-tuned models.", category: "media", tags: ["Art", "Game Assets", "AI"], url: "media.html" },
    { title: "Recraft", desc: "Vector and raster AI image generation.", category: "media", tags: ["Vector", "Design", "AI"], url: "media.html" },
    { title: "Sora 2", desc: "OpenAI's text-to-video generator; web and mobile app.", category: "media", tags: ["Video", "OpenAI", "Generation"], url: "media.html" },
    { title: "Veo 3", desc: "Google's Veo 3.1 video generation in AI Studio.", category: "media", tags: ["Video", "Google", "Generation"], url: "media.html" },
    { title: "Grok Imagine", desc: "xAI's image and video generation.", category: "media", tags: ["Image", "Video", "xAI"], url: "media.html" },
    { title: "Runway", desc: "AI video editing and generation platform.", category: "media", tags: ["Video", "Editing", "AI"], url: "media.html" },
    { title: "Pika", desc: "AI video generation and editing.", category: "media", tags: ["Video", "Generation", "AI"], url: "media.html" },
    { title: "Luma AI", desc: "3D and video AI generation.", category: "media", tags: ["3D", "Video", "AI"], url: "media.html" },
    { title: "ElevenLabs", desc: "AI voice synthesis and cloning.", category: "media", tags: ["Voice", "TTS", "Clone"], url: "media.html" },
    { title: "Suno", desc: "AI music generation from text prompts.", category: "media", tags: ["Music", "Generation", "AI"], url: "media.html" },
    { title: "Udio", desc: "AI-powered music creation platform.", category: "media", tags: ["Music", "Generation", "AI"], url: "media.html" },
    { title: "HeyGen", desc: "AI avatar video generation.", category: "media", tags: ["Avatar", "Video", "AI"], url: "media.html" },
    { title: "Synthesia", desc: "AI video generation with digital avatars.", category: "media", tags: ["Avatar", "Video", "Enterprise"], url: "media.html" },
    { title: "Hugging Face Spaces", desc: "1M+ AI apps: image, video, audio, chat; host and discover.", category: "media", tags: ["Hugging Face", "Spaces", "Apps"], url: "media.html" },
    { title: "Higgsfield", desc: "AI video and image generator: Vibe Motion, Grok Imagine, motion control, cinema studio.", category: "media", tags: ["Video", "Image", "Higgsfield"], url: "media.html" },
    { title: "Kling", desc: "Kuaishou AI video; dynamic motion, action sequences; API.", category: "media", tags: ["Video", "Kuaishou", "API"], url: "media.html" },
    { title: "LTX Video", desc: "Lightricks: 4K at 50fps, audio; local or API; open-source.", category: "media", tags: ["Video", "Lightricks", "Open Source"], url: "media.html" },
    { title: "Agent Opus", desc: "Create videos from ideas: article to video, script to video, motion design, X post to video.", category: "media", tags: ["Video", "Article to Video", "Motion Design"], url: "media.html" },
    { title: "Descript", desc: "All-in-one video & podcast editor; edit by transcribing.", category: "media", tags: ["Video", "Editing", "Audio"], url: "media.html" },

    { title: "OpusClip", desc: "AI video repurposing; turn long videos into shorts.", category: "media", tags: ["Video", "Shorts", "Repurposing"], url: "media.html" },
    { title: "Google Flow", desc: "AI filmmaking with Veo (formerly VideoFX).", category: "media", tags: ["Video", "Google", "Veo"], url: "media.html" },
    { title: "Canva Magic Studio", desc: "All-in-one AI design suite.", category: "media", tags: ["Design", "Image", "AI"], url: "media.html" },
    { title: "Soundraw", desc: "AI music generator for creators; royalty-free.", category: "media", tags: ["Music", "Audio", "Generation"], url: "media.html" },
    { title: "T3 Canvas", desc: "AI image studio: generate, compare, iterate on AI visuals; by theo gg.", category: "media", tags: ["Image", "AI", "theo gg", "T3"], url: "media.html" },

    // === COMPANIES (companies.html) ===
    { title: "OpenAI", desc: "Creator of GPT, DALL-E, and Sora. Leading AI research lab.", category: "company", tags: ["GPT", "ChatGPT", "Sora", "Research"], url: "companies.html" },
    { title: "Anthropic", desc: "AI safety company, creator of Claude.", category: "company", tags: ["Claude", "Safety", "Research"], url: "companies.html" },
    { title: "Google DeepMind", desc: "Google's AI research division behind Gemini.", category: "company", tags: ["Gemini", "Research", "Google"], url: "companies.html" },
    { title: "Meta AI", desc: "Meta's AI division, creators of Llama models.", category: "company", tags: ["Llama", "Open Source", "Meta"], url: "companies.html" },
    { title: "Microsoft", desc: "AI through Azure, Copilot, and OpenAI partnership.", category: "company", tags: ["Copilot", "Azure", "Enterprise"], url: "companies.html" },
    { title: "xAI", desc: "Elon Musk's AI company, creator of Grok.", category: "company", tags: ["Grok", "X", "Elon Musk"], url: "companies.html" },
    { title: "Stability AI", desc: "Creator of Stable Diffusion and open AI models.", category: "company", tags: ["Stable Diffusion", "Open Source", "Image"], url: "companies.html" },
    { title: "Mistral AI", desc: "European AI company with powerful open models (Le Chat).", category: "company", tags: ["Open Source", "European", "Models", "Le Chat"], url: "companies.html" },
    { title: "Codeium", desc: "Forever-free AI coding; Codeium and Windsurf IDE.", category: "company", tags: ["AI Coding", "Free", "Windsurf"], url: "companies.html" },
    { title: "Continue", desc: "Open-source AI coding; VS Code, JetBrains; model-agnostic; free.", category: "company", tags: ["AI Coding", "Open Source", "Free"], url: "companies.html" },
    { title: "Cohere", desc: "Enterprise NLP and embedding models.", category: "company", tags: ["NLP", "Enterprise", "Embeddings"], url: "companies.html" },
    { title: "Perplexity", desc: "AI-powered search engine with citations.", category: "company", tags: ["Search", "AI", "Citations"], url: "companies.html" },
    { title: "Hugging Face", desc: "Models (2M+), datasets (500k+), Spaces (1M+ apps), HuggingChat.", category: "company", tags: ["Open Source", "Models", "Hub"], url: "companies.html" },
    { title: "MongoDB", desc: "Atlas: document DB, vector search, stream processing; AI-ready.", category: "company", tags: ["Database", "Atlas", "Vector Search"], url: "companies.html" },
    { title: "NVIDIA", desc: "AI hardware and software ecosystem leader.", category: "company", tags: ["GPU", "Hardware", "CUDA"], url: "companies.html" },
    { title: "Rosebud AI", desc: "Vibe coding: 2D/3D games and worlds with AI; Game Creator, PixelVibe.", category: "company", tags: ["Game Dev", "AI", "Vibe Coding"], url: "companies.html" },
    { title: "itch.io", desc: "Indie game store: free/paid games, jams, dev portal, assets.", category: "company", tags: ["Games", "Indie", "Dev Portal"], url: "companies.html" },
    { title: "Kuaishou", desc: "Kling: AI video generation; dynamic motion, action sequences; API.", category: "company", tags: ["Video", "Kling", "China"], url: "companies.html" },
    { title: "Lightricks", desc: "LTX Video: 4K at 50fps, audio; local or API; open-source.", category: "company", tags: ["Video", "LTX", "Open Source"], url: "companies.html" },
    { title: "Armor Games", desc: "Free online games: action, puzzle, strategy, MMO, dev portal.", category: "company", tags: ["Games", "Browser", "Free"], url: "companies.html" },
    { title: "Newgrounds", desc: "Classic portal: games, art, audio; Flash legacy, indie community.", category: "company", tags: ["Games", "Indie", "Portal"], url: "companies.html" },
    { title: "PlayHop", desc: "Free browser games platform.", category: "company", tags: ["Games", "Browser", "Free"], url: "companies.html" },
    { title: "Yandex", desc: "Yandex Games: play in browser.", category: "company", tags: ["Games", "Browser", "Yandex"], url: "companies.html" },
    { title: "GitHub", desc: "Developer platform: Copilot, Actions, Codespaces, repos, issues.", category: "company", tags: ["Git", "Copilot", "Repos"], url: "companies.html" },
    { title: "Railway", desc: "All-in-one intelligent cloud: deploy, network, scale, monitor.", category: "company", tags: ["Cloud", "Deploy", "Hosting"], url: "companies.html" },
    { title: "Abacus.AI", desc: "Deep Agent: general agent for apps, reports, presentations; connect to systems.", category: "company", tags: ["Agent", "Apps", "Abacus.AI"], url: "companies.html" },
    { title: "Agent Opus", desc: "Create videos from ideas: article to video, script to video, motion design.", category: "company", tags: ["Video", "Article to Video", "Motion Design"], url: "companies.html" },
    { title: "Anything (Create.xyz)", desc: "Turn words into mobile apps, sites, tools; GPT-5 and 40+ integrations.", category: "company", tags: ["Web Builder", "Apps", "GPT-5"], url: "companies.html" },
    { title: "Builder", desc: "Builder.io: AI frontend engineer; Fusion and Publish; Figma to code, MCP, Cursor/VS Code.", category: "company", tags: ["Frontend", "Figma", "MCP"], url: "companies.html" },
    { title: "Biela", desc: "AI web and app builder: imagine, prompt, create; Claude 4.5 Opus.", category: "company", tags: ["Web Builder", "AI", "Claude"], url: "companies.html" },
    { title: "DeepAI", desc: "Creative AI platform: chat, image, video, music, voice, photo editor; APIs.", category: "company", tags: ["AI", "Image", "Video", "Music"], url: "companies.html" },
    { title: "Design Arena", desc: "Community-driven AI design benchmark: vote to discover which AI is best at design.", category: "company", tags: ["Design", "Benchmark", "AI"], url: "companies.html" },
    { title: "Emergent", desc: "Build full-stack apps, mobile apps and landing pages through conversation; Claude, GitHub.", category: "company", tags: ["Web Builder", "Full-stack", "AI"], url: "companies.html" },
    { title: "Lumio AI", desc: "India's multi-LLM platform: 15+ models (GPT-4o, Claude, Gemini, DeepSeek, Mistral, Grok).", category: "company", tags: ["Multi-model", "India", "LLM"], url: "companies.html" },
    { title: "Squarespace", desc: "Blueprint AI Builder: personalized website in minutes; brand personality, design intelligence.", category: "company", tags: ["Web Builder", "AI", "Design"], url: "companies.html" },
    { title: "Sup AI", desc: "Multi-model orchestration; research-grade accuracy, logprob confidence, always cited.", category: "company", tags: ["Multi-model", "Accuracy", "Orchestration"], url: "companies.html" },
    { title: "Figma", desc: "Collaborative design: Design, Dev Mode, FigJam, Figma Make, MCP for AI.", category: "company", tags: ["Design", "UI", "Collaboration", "MCP"], url: "companies.html" },
    { title: "GDevelop", desc: "Open-source, no-code and AI game engine; 2D, 3D, multiplayer; publish to iOS, Android, Steam, web; event system and AI.", category: "company", tags: ["Game Dev", "Open Source", "No-code", "AI"], url: "companies.html" },
    { title: "Genspark", desc: "AI workspace: Sparkpages, search, presentations, research; 9 models, 80+ tools.", category: "company", tags: ["AI", "Search", "Workspace", "Agent"], url: "companies.html" },
    { title: "Higgsfield", desc: "AI video and image: Vibe Motion, Grok Imagine, Higgsfield Assist creative copilot.", category: "company", tags: ["Video", "Image", "Creative"], url: "companies.html" },
    { title: "Hostinger", desc: "Horizons: no-code AI, 1-click launch; hosting and domain.", category: "company", tags: ["Hosting", "No-code", "AI", "Domain"], url: "companies.html" },
    { title: "Jabali", desc: "AI Game Maker: describe your idea, AI builds your game; no-code 2D and 3D; Jabali Studio (Windows, Mac).", category: "company", tags: ["Game Dev", "Web Builder", "No-code", "AI"], url: "companies.html" },
    { title: "JDoodle", desc: "Online IDE: run and debug code in 70+ languages in the browser.", category: "company", tags: ["IDE", "Browser", "Code Runner"], url: "companies.html" },
    { title: "Jam", desc: "One-click bug reports; auto-capture console, network, repro steps; instant replay; MCP.", category: "company", tags: ["Debug", "QA", "Bug Report", "MCP"], url: "companies.html" },
    { title: "JetBrains", desc: "IntelliJ IDEA: leading IDE for Java and Kotlin; JetBrains AI built-in; refactoring, completion, free tier.", category: "company", tags: ["IDE", "Java", "Kotlin", "IntelliJ"], url: "companies.html" },
    { title: "QuillBot", desc: "Writing tools: paraphrase, grammar, AI detector, plagiarism, humanizer, summarizer.", category: "company", tags: ["Writing", "Grammar", "Paraphrase", "AI Detector"], url: "companies.html" },
    { title: "Vibecode", desc: "AI mobile and web app builder; describe what you want, watch it come to life.", category: "company", tags: ["Web Builder", "Mobile", "AI"], url: "companies.html" },
    { title: "Wix", desc: "AI website builder: create a unique, business-ready website in no time; chat with AI creator.", category: "company", tags: ["Web Builder", "AI", "Website"], url: "companies.html" },
    { title: "Deep Cogito", desc: "Multi-model chat (Cogito 671B, 405B, 109B, 70B).", category: "company", tags: ["Multi-model", "Cogito", "Chat"], url: "companies.html" },
    { title: "Dolphin (dphn.ai)", desc: "Dolphin Chat: chat, bot, models, network, docs.", category: "company", tags: ["Dolphin", "Chat", "Models"], url: "companies.html" },
    { title: "K2 Think (MBZUAI)", desc: "Open-source reasoning model from Mohamed bin Zayed University of AI.", category: "company", tags: ["MBZUAI", "Reasoning", "Open Source"], url: "companies.html" },
    { title: "LongCat", desc: "LongCat AI: think, search, generate image and video.", category: "company", tags: ["LongCat", "Multimodal", "Chat"], url: "companies.html" },
    { title: "Nous Research", desc: "Nous Chat: Hermes models; worldbuilding, code, reasoning.", category: "company", tags: ["Nous", "Hermes", "Chat"], url: "companies.html" },
    { title: "Public AI", desc: "Apertus: open-source LLM from public institution (Switzerland).", category: "company", tags: ["Apertus", "Open Source", "Public AI"], url: "companies.html" },
    { title: "StepFun", desc: "Chat, knowledge-base Q&A, image creation, Step Audio Studio.", category: "company", tags: ["StepFun", "Chat", "Audio"], url: "companies.html" },
    { title: "TII (Falcon)", desc: "Technology Innovation Institute: Falcon H1R 7B, H1 Arabic, open models.", category: "company", tags: ["Falcon", "TII", "Open Source"], url: "companies.html" },
    { title: "Tencent Hunyuan", desc: "Hunyuan AI Studio: dialogue, multimodal, model access, research.", category: "company", tags: ["Tencent", "Hunyuan", "Multimodal"], url: "companies.html" },
    { title: "ZenMux", desc: "Unified gateway to many models; chat and API; compensation for subpar results.", category: "company", tags: ["Multi-model", "API", "Gateway"], url: "companies.html" },
    { title: "Qoder", desc: "Agentic coding platform: IDE, CLI, JetBrains; Editor and Quest modes, Repo Wiki, MCP.", category: "company", tags: ["IDE", "CLI", "Agent"], url: "companies.html" },
    { title: "OpenCode", desc: "Open-source AI coding agent; terminal, desktop, IDE; 75+ LLM providers.", category: "company", tags: ["Open Source", "CLI", "IDE"], url: "companies.html" },
    { title: "Kilo", desc: "Kilo Code: all-in-one agentic engineering platform; VS Code, JetBrains, CLI; #1 on OpenRouter.", category: "company", tags: ["Agent", "IDE", "Open Source"], url: "companies.html" },
    { title: "Kiro", desc: "Amazon: agentic AI development; spec-driven coding.", category: "company", tags: ["Spec-Driven", "Framework", "Amazon"], url: "companies.html" },
    { title: "Roo Code", desc: "Open-source AI dev team; VS Code extension + Cloud agents; model-agnostic.", category: "company", tags: ["Open Source", "IDE", "Agent"], url: "companies.html" },
    { title: "Quests", desc: "Open-source app builder; build and run apps locally with any LLM; BYOK, desktop.", category: "company", tags: ["Web Builder", "Open Source", "Desktop"], url: "companies.html" },
    { title: "Ollama", desc: "Run open models locally; works with Codex, Claude Code, OpenCode, Open WebUI, Msty, etc.", category: "company", tags: ["Local LLM", "Inference", "Open Source"], url: "companies.html" },
    { title: "LM Studio", desc: "Local AI on your computer; run LLMs privately and free; headless (llmster), SDK, MCP, OpenAI-compatible.", category: "company", tags: ["Local LLM", "Inference", "Desktop"], url: "companies.html" },
    { title: "vLLM", desc: "High-throughput inference and serving for LLMs; OpenAI-compatible API; PagedAttention, Hugging Face.", category: "company", tags: ["Local LLM", "Inference", "Serving"], url: "companies.html" },
    { title: "Snyk", desc: "Developer security: find & fix vulnerabilities.", category: "company", tags: ["Security", "DevOps", "AI"], url: "companies.html" },
    { title: "Tabnine", desc: "AI code completion assistant.", category: "company", tags: ["Coding", "IDE", "Assistant"], url: "companies.html" },
    { title: "Sourcegraph", desc: "Code intelligence platform; Cody AI.", category: "company", tags: ["Coding", "Search", "Cody"], url: "companies.html" },
    { title: "Mintlify", desc: "Intelligent docs platform; built for humans and AI; llms.txt, MCP.", category: "company", tags: ["Docs", "MCP", "llms.txt", "Documentation"], url: "companies.html" },
    { title: "Descript", desc: "Video & podcast editing platform.", category: "company", tags: ["Video", "Audio", "Editing"], url: "companies.html" },
    { title: "Canva", desc: "Design platform; Magic Studio AI.", category: "company", tags: ["Design", "Graphics", "AI"], url: "companies.html" },
    { title: "Adobe", desc: "Creative Cloud; Firefly AI models.", category: "company", tags: ["Design", "Creative", "Firefly"], url: "companies.html" },
    { title: "You.com", desc: "AI consumer search engine & chat.", category: "company", tags: ["Search", "Chat", "AI"], url: "companies.html" },
    { title: "T3 (theo gg)", desc: "shoo (auth), T3 Chat, T3 Canvas; by theo gg.", category: "company", tags: ["theo gg", "shoo", "T3 Chat", "T3 Canvas"], url: "companies.html" },


    // === TOOLS (tools.html) ===
    { title: "Cline CLI", desc: "Run tasks headlessly; power GitHub Actions, Discord bots, game characters, Linear tickets.", category: "tool", tags: ["CLI", "Agent", "Headless"], url: "tools.html" },
    { title: "Augment CLI", desc: "AI-powered coding in the terminal; same Context Engine as IDE; #1 on SWE-Bench Pro.", category: "tool", tags: ["CLI", "AI", "Coding"], url: "tools.html" },
    { title: "Zencoder", desc: "Zenflow orchestration + agents; IDE, CLI, Zen Agents; spec-driven, parallel execution.", category: "tool", tags: ["IDE", "CLI", "Agent"], url: "tools.html" },
    { title: "Augment Code", desc: "Context Engine for AI coding; IDE agents, code review, CLI; #1 on SWE-Bench Pro.", category: "tool", tags: ["IDE", "AI", "Coding"], url: "tools.html" },
    { title: "Brave Leo", desc: "Privacy-first AI in Brave; summarize pages, PDFs, translate; Llama, Mixtral, Claude; BYOM, no account.", category: "tool", tags: ["Browser AI", "Privacy", "Leo"], url: "tools.html" },
    { title: "Dia Browser", desc: "AI browser from Arc makers; chat with your tabs, in-line copy editor, tutor in every tab.", category: "tool", tags: ["Browser AI", "Arc", "Tabs"], url: "tools.html" },
    { title: "NVIDIA ChatRTX", desc: "Local personalized chatbot on Windows RTX; RAG, TensorRT-LLM, chat with files, voice, image search.", category: "tool", tags: ["Local LLM", "NVIDIA", "RTX"], url: "tools.html" },
    { title: "Discord Developers", desc: "Build bots, apps, integrations; API, webhooks, rich presence.", category: "tool", tags: ["Discord", "API", "Bots"], url: "tools.html" },
    { title: "WebLLM", desc: "Run LLMs in the browser with WebGPU; MLC-ai; no server needed.", category: "tool", tags: ["Browser", "LLM", "WebGPU"], url: "tools.html" },
    { title: "Zread", desc: "Codebase index: discover repos, trending, MCP; paste repo URL or search by keywords.", category: "tool", tags: ["Codebase", "Index", "MCP", "Repos"], url: "tools.html" },
    { title: "Code Wiki", desc: "Google: Gemini-generated docs for repos; always up-to-date; find open source repos.", category: "tool", tags: ["Codebase", "Google", "Gemini", "Docs"], url: "tools.html" },
    { title: "Algolia", desc: "AI-powered search and discovery; instant, relevant results.", category: "tool", tags: ["Search", "AI", "Discovery"], url: "tools.html" },
    { title: "Abacus AI Deep Agent", desc: "General agent: build apps, reports, presentations; connect to systems, agentic tasks.", category: "tool", tags: ["Agent", "Apps", "Abacus.AI"], url: "tools.html" },
    { title: "Cursor", desc: "AI-first code editor built on VS Code.", category: "tool", tags: ["IDE", "AI", "VS Code"], url: "tools.html" },
    { title: "Windsurf", desc: "AI coding IDE; Cascade agent, Tab autocomplete, MCP, JetBrains plugin.", category: "tool", tags: ["IDE", "AI", "Cascade"], url: "tools.html" },
    { title: "Z Code", desc: "Simple, fast, vibe-ready AI agent; plan, code, review, deploy with your existing tools.", category: "tool", tags: ["IDE", "Agent", "AI"], url: "tools.html" },
    { title: "Codeium", desc: "Forever-free AI coding; completion, chat, 70+ languages; VS Code, JetBrains, Vim.", category: "tool", tags: ["Coding Assistant", "Free", "IDE"], url: "tools.html" },
    { title: "Continue", desc: "Open-source AI coding; VS Code, JetBrains; model-agnostic (Claude, GPT-4, Ollama); free.", category: "tool", tags: ["Coding Assistant", "Open Source", "IDE"], url: "tools.html" },
    { title: "Ghostty", desc: "Fast, feature-rich, cross-platform terminal; GPU acceleration, native UI.", category: "tool", tags: ["Terminal", "GPU", "Cross-platform"], url: "tools.html" },
    { title: "Zed", desc: "High-performance code editor with AI built-in.", category: "tool", tags: ["IDE", "Performance", "Rust"], url: "tools.html" },
    { title: "GitHub Copilot", desc: "AI pair programmer in your IDE.", category: "tool", tags: ["AI", "Coding", "GitHub"], url: "tools.html" },
    { title: "Aider", desc: "AI pair programming in your terminal.", category: "tool", tags: ["CLI", "AI", "Terminal"], url: "tools.html" },
    { title: "Claude Code", desc: "Anthropic's agentic coding tool.", category: "tool", tags: ["CLI", "Anthropic", "Agent"], url: "tools.html" },
    { title: "Gemini CLI", desc: "Google's open-source CLI agent; build, debug & deploy with AI from the terminal; MCP, 1M token context.", category: "tool", tags: ["CLI", "Google", "Terminal"], url: "tools.html" },
    { title: "Gemini CLI GitHub", desc: "Source repo; 94k+ stars, Apache 2.0; contribute, issues, roadmap, docs.", category: "tool", tags: ["CLI", "Google", "Open Source", "GitHub"], url: "tools.html" },
    { title: "OpenAI Codex CLI", desc: "OpenAI's coding assistant CLI.", category: "tool", tags: ["CLI", "OpenAI", "Coding"], url: "tools.html" },
    { title: "Open Interpreter", desc: "Run LLMs in the terminal; execute code, browse, edit files; ChatGPT-like interface.", category: "tool", tags: ["CLI", "Terminal", "Open Source"], url: "tools.html" },
    { title: "Anything (create.xyz)", desc: "Turn words into mobile apps, sites, tools; GPT-5 and 40+ integrations.", category: "tool", tags: ["Web Builder", "Apps", "GPT-5"], url: "tools.html" },
    { title: "Bolt", desc: "AI-powered full-stack app builder.", category: "tool", tags: ["Browser", "Full-stack", "AI"], url: "tools.html" },
    { title: "Biela", desc: "AI web and app builder: imagine, prompt, create; Claude 4.5 Opus.", category: "tool", tags: ["Web Builder", "AI", "Claude"], url: "tools.html" },
    { title: "Builder.io", desc: "AI frontend engineer: design, prototype, ship UI; Fusion and Publish; Figma to code, MCP.", category: "tool", tags: ["Frontend", "Figma", "MCP", "Web Builder"], url: "tools.html" },
    { title: "Builder.io GitHub", desc: "Visual dev platform: SDKs, Figma to code, drag-and-drop; connect to your stack.", category: "tool", tags: ["Frontend", "Figma", "SDK", "GitHub"], url: "tools.html" },
    { title: "Cloudflare AI", desc: "Build AI agents and MCP servers; serverless GPU inference, R2 storage; Agents SDK.", category: "tool", tags: ["AI", "MCP", "Agents", "Inference"], url: "tools.html" },
    { title: "Emergent", desc: "Build full-stack apps, mobile apps and landing pages through conversation; Claude, GitHub.", category: "tool", tags: ["Web Builder", "Full-stack", "AI"], url: "tools.html" },
    { title: "Replit", desc: "Cloud IDE with AI code generation.", category: "tool", tags: ["Browser", "Cloud", "IDE"], url: "tools.html" },
    { title: "Rocket.new", desc: "Think it. Type it. Launch it. Build production-ready web and mobile apps from plain text; no coding.", category: "tool", tags: ["Web Builder", "No-code", "AI"], url: "tools.html" },
    { title: "Firebase", desc: "Google: hosting, Firestore, Auth, Firebase ML, AI (Studio, Gemini in Firebase, Genkit).", category: "tool", tags: ["Google", "Hosting", "Database", "ML"], url: "tools.html" },
    { title: "Firebase Studio", desc: "Google: full-stack AI workspace; build backends, front ends & mobile with Gemini.", category: "tool", tags: ["Google", "Web Builder", "Gemini", "Full-stack"], url: "tools.html" },
    { title: "GDevelop", desc: "Open-source, no-code and AI game engine; 2D, 3D, multiplayer; publish to iOS, Android, Steam, web; event system and AI.", category: "tool", tags: ["Game Dev", "Open Source", "No-code", "AI"], url: "tools.html" },
    { title: "Google AI Studio", desc: "Google's AI development and prototyping workspace.", category: "tool", tags: ["Google", "AI", "Prototyping"], url: "tools.html" },
    { title: "Lovable", desc: "AI-powered app builder; design to deploy.", category: "tool", tags: ["Web Builder", "AI", "Design"], url: "tools.html" },
    { title: "Base44", desc: "Developer platform and tools.", category: "tool", tags: ["Browser", "Platform"], url: "tools.html" },
    { title: "Railway", desc: "Deploy and scale apps; intelligent cloud platform.", category: "tool", tags: ["Deploy", "Cloud", "Hosting"], url: "tools.html" },
    { title: "MongoDB", desc: "Atlas: document DB, vector search, stream processing; AI-ready platform.", category: "tool", tags: ["Database", "Atlas", "Vector Search"], url: "tools.html" },
    { title: "Hugging Face", desc: "Models (2M+), datasets (500k+), Spaces (1M+ apps); Inference, HuggingChat.", category: "tool", tags: ["Models", "Datasets", "Spaces"], url: "tools.html" },
    { title: "StackBlitz", desc: "Instant web development environment.", category: "tool", tags: ["Browser", "Web", "Instant"], url: "tools.html" },
    { title: "v0.dev", desc: "Vercel's AI UI component generator.", category: "tool", tags: ["UI", "Vercel", "Components"], url: "tools.html" },
    { title: "MCP Directory", desc: "Discover 10,000+ MCP servers: PostgreSQL, Google Drive, Puppeteer, Brave Search, Slack, Fetch, Git, GitHub.", category: "tool", tags: ["Reference", "MCP", "Directory"], url: "tools.html" },
    { title: "Localtunnel", desc: "Expose localhost to the web instantly.", category: "tool", tags: ["Tunneling", "Localhost", "Free"], url: "tools.html" },
    { title: "Tunnelmole", desc: "Simple tunneling for local development.", category: "tool", tags: ["Tunneling", "Simple", "Dev"], url: "tools.html" },
    { title: "TRAE", desc: "10x AI engineer; build software solutions independently.", category: "tool", tags: ["IDE", "AI", "Agent"], url: "tools.html" },
    { title: "Warp", desc: "Agentic terminal and IDE with full terminal use.", category: "tool", tags: ["Terminal", "IDE", "Agent"], url: "tools.html" },
    { title: "Kiro", desc: "Agentic AI development; spec-driven coding from prototype to production.", category: "tool", tags: ["IDE", "Agent", "Spec-Driven"], url: "tools.html" },
    { title: "Factory", desc: "Agent-native dev; Droids in IDE, web, CLI, Slack.", category: "tool", tags: ["Agent", "IDE", "Droids"], url: "tools.html" },
    { title: "Figma", desc: "Collaborative interface design: Design, Dev Mode, FigJam, Figma Make, MCP for AI.", category: "tool", tags: ["Design", "UI", "Collaboration", "MCP"], url: "tools.html" },
    { title: "Genspark", desc: "AI workspace: Sparkpages, search, presentations, videos, research; 9 models, 80+ tools.", category: "tool", tags: ["AI", "Search", "Workspace", "Agent"], url: "tools.html" },
    { title: "Hostinger Horizons", desc: "No-code AI partner: tell your idea, 1-click launch, latest LLMs; hosting and domain.", category: "tool", tags: ["Web Builder", "No-code", "AI", "Hosting"], url: "tools.html" },
    { title: "Jabali", desc: "AI Game Maker: describe your idea, AI builds your game; no-code 2D and 3D; Jabali Studio (Windows, Mac).", category: "tool", tags: ["Game Dev", "Web Builder", "No-code", "AI"], url: "tools.html" },
    { title: "JDoodle", desc: "Online IDE: run and debug code in 70+ languages in the browser.", category: "tool", tags: ["Browser", "IDE", "Code Runner"], url: "tools.html" },
    { title: "LLMChat", desc: "Go deeper: AI-powered research and agentic workflows in the browser.", category: "tool", tags: ["AI", "Research", "Agent", "Browser"], url: "tools.html" },
    { title: "Manus", desc: "Hands On AI (Meta): create slides, build websites, develop apps from prompts.", category: "tool", tags: ["Meta", "Web Builder", "AI", "Slides"], url: "tools.html" },
    { title: "QuillBot", desc: "Writing: paraphrase, grammar, AI detector, plagiarism, humanizer, translate, summarizer.", category: "tool", tags: ["Writing", "Grammar", "Paraphrase", "AI Detector"], url: "tools.html" },
    { title: "Wikipedia Artificial Intelligence", desc: "Overview of AI: goals, techniques, applications, ethics, history.", category: "tool", tags: ["Reference", "AI", "Wikipedia"], url: "tools.html" },
    { title: "Wikipedia List of LLMs", desc: "Reference list of large language models with parameters, licenses, notes.", category: "tool", tags: ["Reference", "LLM", "Wikipedia"], url: "tools.html" },
    { title: "Google Antigravity", desc: "Google's agentic IDE; autonomous agents across editor, terminal, browser.", category: "tool", tags: ["Google", "IDE", "Agent"], url: "tools.html" },
    { title: "Android Studio", desc: "Official Android IDE with Gemini in Android Studio.", category: "tool", tags: ["Android", "IDE", "Google"], url: "tools.html" },
    { title: "Kimi Code CLI", desc: "Moonshot AI terminal agent; MCP, ACP, VS Code extension.", category: "tool", tags: ["CLI", "Moonshot", "MCP"], url: "tools.html" },
    { title: "Mistral Vibe", desc: "Mistral's open-source CLI coding assistant; skills, MCP.", category: "tool", tags: ["CLI", "Mistral", "MCP"], url: "tools.html" },
    { title: "Crush", desc: "Charm's agentic CLI; multi-model, LSP, MCP, sessions.", category: "tool", tags: ["CLI", "Charm", "Agent"], url: "tools.html" },
    { title: "Qwen Code", desc: "QwenLM open-source terminal agent; OAuth free tier, IDE integration.", category: "tool", tags: ["CLI", "Qwen", "Open Source"], url: "tools.html" },
    { title: "Qoder CLI", desc: "Terminal-native agentic coding; fix, review, automate; <70ms startup, CI/CD.", category: "tool", tags: ["CLI", "Qoder", "Agent"], url: "tools.html" },
    { title: "OpenCode", desc: "Open-source AI coding agent; terminal, desktop, IDE; 75+ LLM providers, LSP, multi-session.", category: "tool", tags: ["CLI", "IDE", "Open Source"], url: "tools.html" },
    { title: "Kilo Code", desc: "All-in-one agentic engineering platform; VS Code, JetBrains, CLI; #1 on OpenRouter.", category: "tool", tags: ["CLI", "IDE", "Agent"], url: "tools.html" },
    { title: "Roo Code", desc: "Open-source AI dev team; VS Code extension + Cloud agents; model-agnostic, role modes.", category: "tool", tags: ["CLI", "IDE", "Open Source"], url: "tools.html" },
    { title: "Qoder", desc: "Agentic coding platform: IDE, CLI, JetBrains; Editor and Quest modes, Repo Wiki, MCP.", category: "tool", tags: ["IDE", "Qoder", "Agent"], url: "tools.html" },
    { title: "IBM Project Bob", desc: "IBM's AI software dev partner; chat in editor, code review, vulnerability and secrets detection.", category: "tool", tags: ["IDE", "IBM", "Agent"], url: "tools.html" },
    { title: "IntelliJ IDEA", desc: "Leading IDE for Java and Kotlin; JetBrains AI built-in; refactoring, completion, free tier.", category: "tool", tags: ["IDE", "Java", "Kotlin", "JetBrains"], url: "tools.html" },
    { title: "bolt.diy", desc: "Open-source Bolt: prompt, run, edit and deploy full-stack apps with any LLM; 19+ providers, MCP, Electron.", category: "tool", tags: ["Web Builder", "Open Source", "Full-stack"], url: "tools.html" },
    { title: "Quests", desc: "Open-source app builder; build and run apps locally with any LLM; BYOK, desktop, templates.", category: "tool", tags: ["Web Builder", "Open Source", "Desktop"], url: "tools.html" },
    { title: "shoo", desc: "Auth in 2 lines of code. Free, open source. By theo gg.", category: "tool", tags: ["Auth", "Open Source", "theo gg"], url: "tools.html" },
    { title: "Spec Kit", desc: "GitHub: Spec-Driven Development toolkit; specs become executable; Specify CLI, works with Qoder, Cursor, OpenCode.", category: "tool", tags: ["Reference", "Spec-Driven", "CLI"], url: "tools.html" },
    { title: "shoo", desc: "Auth in 2 lines of code. Free, open source. By theo gg.", category: "tool", tags: ["Auth", "Open Source", "theo gg", "Free"], url: "tools.html" },
    { title: "Squoosh", desc: "Quick, simple image compression; Google; WebP, AVIF, resize.", category: "tool", tags: ["Image", "Compression", "WebP", "AVIF"], url: "tools.html" },
    { title: "Squoosh", desc: "Quick, simple image compression; Google; WebP, AVIF, resize.", category: "tool", tags: ["Image", "Compression", "Google"], url: "tools.html" },
    { title: "Ollama", desc: "Easiest way to run open models locally; works with Codex, Claude Code, OpenCode, Open WebUI, Msty, etc.", category: "tool", tags: ["Local LLM", "Inference", "Open Source"], url: "tools.html" },
    { title: "LM Studio", desc: "Local AI on your computer; run LLMs privately and free; headless (llmster), SDK, MCP, OpenAI-compatible API.", category: "tool", tags: ["Local LLM", "Inference", "Desktop"], url: "tools.html" },
    { title: "vLLM", desc: "High-throughput, memory-efficient inference and serving for LLMs; OpenAI-compatible API; PagedAttention, Hugging Face.", category: "tool", tags: ["Local LLM", "Inference", "Serving"], url: "tools.html" },
    { title: "DeepAI", desc: "All-in-one creative AI: chat, image, video, music, voice, photo editor; APIs.", category: "tool", tags: ["AI", "Image", "Video", "Music"], url: "tools.html" },
    { title: "Docker", desc: "Containers, MCP catalog, agentic stack with Compose.", category: "tool", tags: ["Containers", "MCP", "DevOps"], url: "tools.html" },
    { title: "Claude (desktop & mobile)", desc: "Download Claude app for macOS, Windows, iOS, Android.", category: "tool", tags: ["Claude", "Download", "Anthropic"], url: "tools.html" },
    { title: "HTML Online Viewer", desc: "Edit and preview HTML in the browser; format, highlight.", category: "tool", tags: ["HTML", "Browser", "Preview"], url: "tools.html" },
    { title: "Wispr Flow", desc: "AI voice dictation; speech to polished text in every app (Mac, Windows, iPhone).", category: "tool", tags: ["Voice", "Speech-to-text", "Dictation"], url: "tools.html" },
    { title: "Rosebud AI", desc: "Vibe coding: make 2D/3D games and worlds with AI; no code, browser.", category: "tool", tags: ["Game Dev", "AI", "Vibe Coding"], url: "tools.html" },
    { title: "itch.io (game dev)", desc: "Indie dev portal: publish games, assets, jams, dev logs.", category: "tool", tags: ["Game Dev", "Indie", "Portal"], url: "tools.html" },
    { title: "findmypapers.ai", desc: "Semantic search for 300,000+ AI research papers; find, compare, explain with citations.", category: "tool", tags: ["Research", "Papers", "Semantic Search"], url: "tools.html" },
    { title: "Squarespace AI", desc: "Blueprint AI Builder: personalized website in minutes; brand personality, design intelligence.", category: "tool", tags: ["Web Builder", "AI", "Design"], url: "tools.html" },
    { title: "There's An AI For That", desc: "Directory of 45,800+ AI tools for 11,356 tasks; search, categories, just released.", category: "tool", tags: ["Directory", "AI Tools", "Reference"], url: "tools.html" },
    { title: "Arena", desc: "Benchmark & compare the best AI models; experience the frontier; battle, leaderboard, file upload.", category: "tool", tags: ["Benchmark", "Multi-model", "Leaderboard"], url: "tools.html" },
    { title: "Design Arena", desc: "Community-driven AI design benchmark: vote to discover which AI is best at design (website, image, video, UI).", category: "tool", tags: ["Design", "Benchmark", "AI"], url: "tools.html" },
    { title: "Vibecode", desc: "AI mobile and web app builder; describe what you want, watch it come to life; Claude.", category: "tool", tags: ["Web Builder", "Mobile", "AI"], url: "tools.html" },
    { title: "Wix AI", desc: "Create a unique, business-ready website in no time with AI; chat with AI website creator.", category: "tool", tags: ["Web Builder", "AI", "Website"], url: "tools.html" },
    { title: "Amazon Q Developer", desc: "AWS: AI coding companion; completion, refactoring.", category: "tool", tags: ["Coding", "AWS", "IDE"], url: "tools.html" },
    { title: "CodeGPT", desc: "VS Code extension; chat with code, refactor, document.", category: "tool", tags: ["Coding", "IDE", "VS Code"], url: "tools.html" },
    { title: "Jam", desc: "One-click bug reports devs love; auto-capture console, network, repro steps; instant replay; MCP.", category: "tool", tags: ["Debug", "QA", "Bug Report", "MCP"], url: "tools.html" },
    { title: "Mintlify", desc: "Intelligent docs platform; built for humans and AI; llms.txt, MCP, self-updating agent.", category: "tool", tags: ["Docs", "MCP", "llms.txt", "Documentation"], url: "tools.html" },
    { title: "Snyk", desc: "Developer security platform; AI-powered vulnerability finding.", category: "tool", tags: ["Security", "DevOps", "Tool"], url: "tools.html" },
    { title: "Sourcegraph Cody", desc: "AI coding assistant; codebase-aware chat and autocomplete.", category: "tool", tags: ["Coding", "IDE", "Cody"], url: "tools.html" },
    { title: "Tabnine", desc: "AI code completion; private, secure, works offline.", category: "tool", tags: ["Coding", "IDE", "Offline"], url: "tools.html" },
    { title: "Z.ai GLM Coding Plan", desc: "GLM-5 & GLM-4.7 for agents & IDEs; API for Claude Code, Cursor, Cline, Kilo Code, Roo Code, Crush, Gemini CLI; Lite/Pro/Max, MCP.", category: "tool", tags: ["Coding Plan", "API", "Zhipu", "GLM", "IDE"], url: "tools.html" },
    { title: "Jan", desc: "Open-source ChatGPT alternative; run 100% offline.", category: "tool", tags: ["Local LLM", "Offline", "Desktop"], url: "tools.html" },
    { title: "Msty", desc: "Easiest local AI app; Works with Ollama; highly polished UI.", category: "tool", tags: ["Local LLM", "Desktop", "UI"], url: "tools.html" },
    { title: "Open WebUI", desc: "Extensible self-hosted WebUI (formerly Ollama WebUI).", category: "tool", tags: ["Local LLM", "WebUI", "Self-hosted"], url: "tools.html" },

    { title: "You.com", desc: "The AI search engine; chat, write, code, create images.", category: "tool", tags: ["Search", "Chat", "Browser"], url: "tools.html" },

    // === SPECIALS (specials.html) ===
    { title: "Gemini Code Assist (free)", desc: "Google: free preview for students, hobbyists, startups; AI coding in IDE.", category: "special", tags: ["Free", "AI Coding", "Google", "IDE"], url: "specials.html" },
    { title: "p5js AI", desc: "Free cloud IDE for p5.js; GPT-5.1, Claude 4.5, Gemini; no account required.", category: "special", tags: ["Free", "IDE", "Creative Coding", "p5.js"], url: "specials.html" },
    { title: "DigitalPlat FreeDomain", desc: "Get free domain names for your projects.", category: "special", tags: ["Domain", "Free", "Hosting"], url: "specials.html" },
    { title: "freeCodeCamp", desc: "Learn to code for free with comprehensive curriculum.", category: "special", tags: ["Learning", "Free", "Coding"], url: "specials.html" },
    { title: "The Odin Project", desc: "Full-stack curriculum for web development.", category: "special", tags: ["Learning", "Full-stack", "Free"], url: "specials.html" },
    { title: "itch.io", desc: "Indie game store: free/paid games, jams, dev portal, assets.", category: "special", tags: ["Games", "Indie", "Dev Portal"], url: "specials.html" },
    { title: "Armor Games", desc: "Free online games: action, puzzle, strategy, RPG, MMO.", category: "special", tags: ["Games", "Browser", "Free"], url: "specials.html" },
    { title: "PlayHop", desc: "Free browser games platform.", category: "special", tags: ["Games", "Browser", "Free"], url: "specials.html" },
    { title: "Newgrounds", desc: "Classic portal: games, art, audio; Flash legacy, indie dev.", category: "special", tags: ["Games", "Indie", "Portal"], url: "specials.html" },
    { title: "Yandex Games", desc: "Yandex game portal: play in browser.", category: "special", tags: ["Games", "Browser", "Yandex"], url: "specials.html" },

    // === PAGES ===
    { title: "Home", desc: "Ryan Otterdays developer profile and overview.", category: "page", tags: ["Profile", "Home", "About"], url: "index.html" },
    { title: "Programs", desc: "Browse 60+ projects including games, tools, and AI projects.", category: "page", tags: ["Projects", "Portfolio", "Code"], url: "programs.html" },
    { title: "AI Chats", desc: "Links to AI chat platforms and assistants.", category: "page", tags: ["AI", "Chat", "Assistants"], url: "chats.html" },
    { title: "Media Gen", desc: "AI media generation tools for video, image, and audio.", category: "page", tags: ["Media", "Generation", "AI"], url: "media.html" },
    { title: "Companies", desc: "55+ AI and tech companies directory.", category: "page", tags: ["Companies", "Directory", "AI"], url: "companies.html" },
    { title: "Tools", desc: "Developer tools including CLI, IDE, and browser tools.", category: "page", tags: ["Tools", "Developer", "IDE"], url: "tools.html" },
    { title: "Specials", desc: "Free resources, domains, learning, and games (itch.io, Armor Games, PlayHop, Newgrounds, Yandex Games).", category: "page", tags: ["Free", "Resources", "Learning", "Games"], url: "specials.html" },
    { title: "Skills/Tools", desc: "IDE skills, Cursor agentic tools, Google Antigravity agentic tools (file, search, browser, etc.), and MCPs.", category: "page", tags: ["Cursor", "Antigravity", "IDE", "MCP", "Skills", "Tools", "Agent"], url: "skills.html" },
    { title: "SkillBox", desc: "Utility AI agent skills: track-session, git-worktree, generate-skill, ideal-react-component, rate-skill. Works with Cursor, Codex, Gemini CLI, OpenCode, Replit, 40+ agents.", category: "tool", tags: ["Skills", "Vercel", "Claude Code", "Cursor", "Agent", "SKILL.md"], url: "skills.html" },
    { title: "Skills directory", desc: "Discover skills by category: React, Testing, Git & workflows. npx skills find [query], skills.sh.", category: "page", tags: ["Skills", "Vercel", "React", "Testing", "Git", "find-skills"], url: "skills.html" },
    { title: "About", desc: "What this site is: projects and tools worth sharing. Every link is safe and direct.", category: "page", tags: ["About", "Site", "Links"], url: "about.html" },
    { title: "Updates", desc: "Site update log: version history, new features, fixes, and changes.", category: "page", tags: ["Updates", "Changelog", "Version"], url: "updates.html" },
    { title: "Explore", desc: "Visual breakdown of all indexed data: categories, tags, and page distribution.", category: "page", tags: ["Data", "Visualization", "Stats", "Explore"], url: "explore.html" },
    { title: "Inspirations", desc: "People and projects that inspire: theo gg (shoo, T3 Chat, T3 Canvas).", category: "page", tags: ["Inspirations", "theo gg", "About"], url: "about.html" },
    { title: "Dev tips", desc: "Trigger mobile view in Chrome: F12 (or Cmd+Option+I on Mac), then Toggle Device Toolbar.", category: "page", tags: ["Dev", "Chrome", "F12", "Mobile", "Debug"], url: "about.html" }
];
